### ISSUE TITLE
The multi-task setup

### ISSUE THREAD

**Issue by ReinholdM** [NM512/dreamerv3-torch#1]
Hi! This is awesome reimplementation work and thanks a lot! Could you point out the multi-task setup for the configuration on DM_control or other possible benchmarks?

**Comment by NM512** [comment]
Thank you for asking! As for task setup, I plan to evaluate on as many tasks as possible starting from visual DMC suite. Unfortunately, due to limited resources and time, it will take some time.

**Comment by ReinholdM** [comment]
Thank you for the quick reply. Maybe, there could be a detailed to-do list that includes the future possible tasks. :)

**Comment by NM512** [comment]
I'm sure it's a useful list. I will try to add it in the near future.

**Comment by NM512** [comment]
Thank you for your patience.
I added a detailed to-do list.
