### ISSUE TITLE
Plan for evaluating crafter

### ISSUE THREAD

**Issue by shell769324** [NM512/dreamerv3-torch#10]
Hi, really appreciate the work. Just curious, do you have any plan for evaluating this with crafter?

**Comment by NM512** [comment]
Hi,

I don't have plans to evaluate on Crafter so far.
Because it requires a much bigger network that cannot be run on my poor GPU. :(

<img src="https://github.com/NM512/dreamerv3-torch/assets/70328564/ace1800f-7fb7-4337-9576-ce75c2e883b2" width="500" height="550" />

**Comment by NM512** [comment]
@RajeshDM

I guess it will take 2~3 days to run.
Please wait until I prepare Crafter environment code first!
Thank you very much for your cooperation!

**Comment by NM512** [comment]
@RajeshDM 

Hi,
I added Crafter environment at [latest commit](https://github.com/NM512/dreamerv3-torch/commit/5dce8cf13bc104e4f93969570678e82cf9527b36).
If you are still interested in contributing the community, please give a try.

```
pip install crafter==1.8.0
python3 dreamer.py --configs crafter --logdir ./logdir/crafter
```

Thanks in advance.

Best regards,
NM512

**Comment by RajeshDM** [comment]
> @RajeshDM
> 
> Hi, I added Crafter environment at [latest commit](https://github.com/NM512/dreamerv3-torch/commit/5dce8cf13bc104e4f93969570678e82cf9527b36). If you are still interested in contributing the community, please give a try.
> 
> ```
> pip install crafter==1.8.0
> python3 dreamer.py --configs crafter --logdir ./logdir/crafter
> ```
> 
> Thanks in advance.
> 
> Best regards, NM512

I will try running sometime next week. Thank you for the updated code. Let me know if you want something else run as well.

**Comment by NM512** [comment]
@RajeshDM 
Thank you so much.
It is really helpful if you can send the tensorboard(file with name starting from events.out.~) result to my e-mail after finishing the 1st run.

**Comment by RajeshDM** [comment]
@NM512 

I'm currently running it. Could you please send me your e-mail address, I will send it. 
Also, it's been running for 3 days now. The current status is :

Train episode has 179 steps and return 7.1.
[292513] dataset_size 292513.0 / train_return 7.1 / train_length 179.0 / train_episodes 1657.0
[292522] model_loss 5.2 / model_grad_norm 30.9 / image_loss 2.6 / reward_loss 0.0 / cont_loss 0.0 / kl_free 1.0 / dyn_scale 0.5 / rep_scale 0.1 / dyn_loss 4.2 / rep_loss 4.2 / kl 4.1 / prior_ent 42.7 / post_ent 38.6 / normed_target_mean 0.3 / normed_target_std 0.3 / normed_target_min -0.2 / normed_target_max 1.6 / EMA_005 -0.2 / EMA_095 4.9 / value_mean 1.6 / value_std 1.7 / value_min -0.7 / value_max 7.5 / target_mean 1.6 / target_std 1.7 / target_min -1.0 / target_max 8.0 / imag_reward_mean 0.0 / imag_reward_std 0.2 / imag_reward_min -0.7 / imag_reward_max 1.0 / imag_action_mean 4.4 / imag_action_std 3.2 / imag_action_min 0.0 / imag_action_max 16.0 / actor_entropy 0.2 / actor_loss -0.0 / actor_grad_norm 0.2 / value_loss 1.6 / value_grad_norm 1.1 / update_count 145100.0 / fps 1.4
Train episode has 172 steps and return 6.1.
[292685] dataset_size 292685.0 / train_return 6.1 / train_length 172.0 / train_episodes 1658.0
[292685] 
Start evaluation.
Eval episode has 222.8 steps and return 7.1.
[292685] eval_return 7.1 / eval_length 222.8 / eval_episodes 10.0


Any estimate on how much longer it will run?

**Comment by ClashLuke** [comment]
Hi, I could run it on one `p4d.24xlarge` for up to 7 days.
![image](https://github.com/NM512/dreamerv3-torch/assets/39779310/901366fd-8e38-459b-838c-4d0173d266bd)
Unfortunately, a multi-node setup is currently impossible, so I hope that's large enough.

Do you have a self-contained docker container containing all dependencies I could run?

**Comment by zdx3578** [comment]
> @NM512
> 
> I'm currently running it. Could you please send me your e-mail address, I will send it. Also, it's been running for 3 days now. The current status is :
> 
> Train episode has 179 steps and return 7.1. [292513] dataset_size 292513.0 / train_return 7.1 / train_length 179.0 / train_episodes 1657.0 [292522] model_loss 5.2 / model_grad_norm 30.9 / image_loss 2.6 / reward_loss 0.0 / cont_loss 0.0 / kl_free 1.0 / dyn_scale 0.5 / rep_scale 0.1 / dyn_loss 4.2 / rep_loss 4.2 / kl 4.1 / prior_ent 42.7 / post_ent 38.6 / normed_target_mean 0.3 / normed_target_std 0.3 / normed_target_min -0.2 / normed_target_max 1.6 / EMA_005 -0.2 / EMA_095 4.9 / value_mean 1.6 / value_std 1.7 / value_min -0.7 / value_max 7.5 / target_mean 1.6 / target_std 1.7 / target_min -1.0 / target_max 8.0 / imag_reward_mean 0.0 / imag_reward_std 0.2 / imag_reward_min -0.7 / imag_reward_max 1.0 / imag_action_mean 4.4 / imag_action_std 3.2 / imag_action_min 0.0 / imag_action_max 16.0 / actor_entropy 0.2 / actor_loss -0.0 / actor_grad_norm 0.2 / value_loss 1.6 / value_grad_norm 1.1 / update_count 145100.0 / fps 1.4 Train episode has 172 steps and return 6.1. [292685] dataset_size 292685.0 / train_return 6.1 / train_length 172.0 / train_episodes 1658.0 [292685] Start evaluation. Eval episode has 222.8 steps and return 7.1. [292685] eval_return 7.1 / eval_length 222.8 / eval_episodes 10.0
> 
> Any estimate on how much longer it will run?

[morihira3513@gmail.com](mailto:morihira3513@gmail.com)

**Comment by NM512** [comment]
@RajeshDM

Apologies for my delayed response.
Could you kindly send the data to [morihira3513@gmail.com](mailto:morihira3513@gmail.com)?
Considering the task's requirements, it appears that completing it will likely take around 6 more days as we need to reach 1 million steps.

**Comment by NM512** [comment]
@ClashLuke

Thank you for sharing the valuable information.
Regarding your question about a self-contained docker container with all the dependencies, I'm afraid I don't have one available at the moment.

**Comment by ClashLuke** [comment]
Ah, that's unfortunate. Let me know when you have a command. I can run. The instance is ready:
![image](https://github.com/NM512/dreamerv3-torch/assets/39779310/0469465a-8da0-4864-b358-b3f19b6d3529)

**Comment by RajeshDM** [comment]
> @RajeshDM
> 
> Apologies for my delayed response. Could you kindly send the data to [morihira3513@gmail.com](mailto:morihira3513@gmail.com)? Considering the task's requirements, it appears that completing it will likely take around 6 more days as we need to reach 1 million steps.

I have completed the run. Unfortunately it took 8 days and it ran upto 980,000 steps instead of 1 million. I will mail the results to you

**Comment by NM512** [comment]
@RajeshDM
Thank you very much for your cooperation. I've updated the Crafter results on the top page.
I'll keep you posted if I'm able to speed up the code.
