### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ATriplez** [NM512/dreamerv3-torch#13]
Hi,

I'm curious that is there some modifications in this repo compared to the tensorflow version, cause I find this repo outperforms the original in some tasks such as quadruped-walk and acrobot-swingup. Is this repo tweaked for hyperparameters or is there a slight difference in model structure?

Thanks in advance.

**Comment by NM512** [comment]
Hello,

I intentionally did not make any modifications with the aim of improving the performance. While I didn't directly translate the JAX implementation from the author into PyTorch, there might be slight differences in the implementation. Furthermore, in deep reinforcement learning, there are factors such as task stochasticity and the impact of variance intrinsic to the methods and seeds, making it challenging to achieve exact reproducibility of results from the latest research papers.

Let me share an interesting paper with you. Figure 6 in this paper is one of my favorite one, and I think you might find it intriguing.
[Deep Reinforcement Learning that Matters](https://arxiv.org/abs/1709.06560)

Feel free to let me know if there's anything else I can assist you with!
