### ISSUE TITLE
Shifted value for return computation

### ISSUE THREAD

**Issue by burchim** [NM512/dreamerv3-torch#16]
Hi,

Thanks for the implementation!

I noticed a small difference with the original implementation while looking at the code.
When computing the target returns, the official DreamerV3 implementation uses the classic bellman equation  with rewards[1:], discounts[1:] etc such that Value(t) = reward(t+1) + discount(t+1) * Value(t+1). [here](https://github.com/danijar/dreamerv3/blob/423291a9875bb9af43b6db7150aaa972ba889266/dreamerv3/agent.py#L359)

However, in your implementation I noticed that you use the DreamerV2 way of shifting the value with Value(t) = reward(t) + discount(t) * Value(t+1) using rewards[:-1], discounts[:-1] etc. [here](https://github.com/danijar/dreamerv2/blob/07d906e9c4322c6fc2cd6ed23e247ccd6b7c8c41/dreamerv2/agent.py#L317) where reward(t) is the reward of the current state (same as the value) instead of being the one of next state.

So I wanted to know if you also experimented using the DreamerV3 way of predicting next rewards in the value function.
Both approaches seams to work similarly in practice

Also, I suppose the normal weight init should be:
`nn.init.trunc_normal_(m.weight.data, mean=0.0, std=std, a=-2.0*std, b=2.0*std)`
instead of:
`nn.init.trunc_normal_(m.weight.data, mean=0.0, std=std, a=-2.0, b=2.0)`
to correctly trunc the weights values outside 2 standard deviations [here](https://github.com/NM512/dreamerv3-torch/blob/6c861ca7cb5d59754da508abb6ce6599a503124a/tools.py#L807).

Best,
Maxime

**Comment by NM512** [comment]
Thanks for sharing your notices!
It surelly seems that the author's implementation doesn't include reward[t] in bellman equation.

I noticed that I was performing unnecessary calculations.
Because when calculating the loss for the Actor, the reward[t] term is cancelled out when subtracting Base from Value to compute the Advantage, and then it is further rescaled using EMA. 
While the impact must be small, I will check the effect of that difference.

Additionally, you are correct about the trunc_normal initializer. 
Thank you very much for your really useful contribution!

Best regards,
NM512

**Comment by burchim** [comment]
Happy that I could help!

Yes the reward term should be somewhat canceled while computing the advantage since we do not use the next reward depending of the action taken, but not the gradient.

Also, I noticed that you use a single training environment in the [config](https://github.com/NM512/dreamerv3-torch/blob/6c861ca7cb5d59754da508abb6ce6599a503124a/configs.yaml#L24) while the author uses 4 for better exploration I suppose.
Did you train 1M env steps with a single environment in the case of visual DMC?

I am trying to recover the paper results.

**Comment by NM512** [comment]
Thanks for your comment!

Yes, I used single environment without notice of that written in the paper. I will check that effect too. 

I'm glad to hear that you are trying to reproduce the paper results.
Please kindly let me know if you could find something. It is also really helpful if you can share the results of your challenge.

Thank you very much again!

Best,
NM512

**Comment by NM512** [comment]
@burchim 
I modified several lines of code according to the paper.
Thanks you for your help.

**Comment by burchim** [comment]
You welcome :)

I am happy to help! I will let you know if I find other bugs in the code.

Reinforcement learning papers aren't the easiest to reproduce ^^
