### ISSUE TITLE
will add memory-maze env ?

### ISSUE THREAD

**Issue by zdx3578** [NM512/dreamerv3-torch#18]
https://github.com/jurgisp/memory-maze/

**Comment by zdx3578** [comment]
diff --git a/configs.yaml b/configs.yaml
index 332a977..6074feb 100644
--- a/configs.yaml
+++ b/configs.yaml
@@ -148,9 +148,26 @@ atari100k:
   imag_gradient: 'reinforce'
   time_limit: 108000
   prefill: 1
   batch_size: 10
   batch_length: 20
+
+mazegym:
+  #task: "memory_maze:MemoryMaze-9x9-v0"
+  steps: 5e4
+  action_repeat: 2
+
diff --git a/dreamer.py b/dreamer.py
index 36eb633..35f1e57 100644
--- a/dreamer.py
+++ b/dreamer.py
@@ -210,6 +210,15 @@ def make_env(config, logger, mode, train_eps, eval_eps):
             task, mode if "train" in mode else "test", config.action_repeat
         )
         env = wrappers.OneHotAction(env)
+    elif suite == "mazegym":
+        import gym
+        env = gym.make('memory_maze:MemoryMaze-9x9-v0')
+        env = wrappers.OneHotAction(env)

     else:
         raise NotImplementedError(suite)
     env = wrappers.TimeLimit(env, config.time_limit)


run: python3 dreamer.py --configs mazegym --task mazegym_9  --logdir ./logdir/maze99
error:

  File "/home/jz/github/dreamerv3-torch-zdx/dreamer.py", line 415, in <module>
    main(parser.parse_args(remaining))
  File "/home/jz/github/dreamerv3-torch-zdx/dreamer.py", line 355, in main
    tools.simulate(random_agent, train_envs, prefill)
  File "/home/jz/github/dreamerv3-torch-zdx/tools.py", line 141, in simulate
    results = [envs[i].reset() for i in indices]
  File "/home/jz/github/dreamerv3-torch-zdx/tools.py", line 141, in <listcomp>
    results = [envs[i].reset() for i in indices]
  File "/home/jz/github/dreamerv3-torch-zdx/envs/wrappers.py", line 193, in reset
    obs = self._env.reset()
  File "/home/jz/github/dreamerv3-torch-zdx/envs/wrappers.py", line 53, in reset
    transition["reward"] = 0.0
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices


maze reward:         https://github.com/jurgisp/memory-maze/blob/08e3676156d0af36ddea6087ba68edd46b71007c/memory_maze/gym_wrappers.py#L30

**Comment by NM512** [comment]
Hi,

Thank you for suggesting adding a new benchmark task.
Unfortunatelly I don't have plan to add [memory-maze](https://github.com/jurgisp/memory-maze) to benchmarks even though that environment seems interesting.

I would greatly appreciate it if you could contribute to the implementation. 
If you decide to do so, please refer to the implementation of other environments in the "env" folder.
You are welcome to ask any questions you may have.

Best regards,
NM512

**Comment by zdx3578** [comment]
just running

<img width="525" alt="image" src="https://github.com/NM512/dreamerv3-torch/assets/382863/945213a9-9ffd-4592-a67b-cea0754e1b70">

**Comment by NM512** [comment]
Thank you very much for sharing the progress!
Please let me know when you have difficulties.

Best regards,
NM512

**Comment by zdx3578** [comment]
<img width="757" alt="image" src="https://github.com/NM512/dreamerv3-torch/assets/382863/c89b7389-cace-4b12-81d8-c808b857b249">

**Comment by jurgisp** [comment]
Very nice, thanks for running this!

**Comment by zdx3578** [comment]
<img width="863" alt="image" src="https://github.com/NM512/dreamerv3-torch/assets/382863/81f74353-ca3c-4585-a1eb-804ac2b0eb71">

**Comment by NM512** [comment]
Thanks for implementing the code to test in new benchmark task!
Are you interested in making a pull request so that anyone interested can play with it?

**Comment by zdx3578** [comment]
yes， The code is messy and needs to be sorted out.

**Comment by NM512** [comment]
Memory-maze environment was merged at [this commit](https://github.com/NM512/dreamerv3-torch/commit/775eb94e7f89548e02a7433ea207bf6ae021e259).
