### ISSUE TITLE
Plan2explore 

### ISSUE THREAD

**Issue by TachikakaMin** [NM512/dreamerv3-torch#19]
Hi, thanks for your contribution.

I'm just wondering: have you tested your code in plan2explore experiment setting and can you show some results? I saw you updated your code with plan2explore code.

@NM512 

Thanks.

**Comment by NM512** [comment]
Hi,

Thanks for asking.
I haven't executed any performance check regarding plan2explore.
I was wondering what kind of tests are suitable.
Let me know if there are some advices.

Best regards,
NM512
