### ISSUE TITLE
will add this greate memory cell?

### ISSUE THREAD

**Issue by zdx3578** [NM512/dreamerv3-torch#22]
https://github.com/NeuromorphicComputing/STPN

Short-Term Plasticity Neurons Learning to Learn and Forget

**Comment by zdx3578** [comment]
how  check the impact  ?  first incorporate the code and try run ? through the paper, STPN is good.

**Comment by NM512** [comment]
Yes, first incorporate the code and try run in forked branch.
We need to check the performance as a case of combining with Dreamerv3 even though that looks nice in the paper.

> whats diff batch_length in eval and train ?

"batch_length" is only used for training. Please check Backpropagation Through Time(BPTT).

> batchsize diff in eval and train, how this implement?

I can't say without reading the paper. I'll try to take a look when I have time!

Anyway, thanks for suggesting incorporationg the new method.

**Comment by zdx3578** [comment]
temp code : https://github.com/zdx3578/dreamerv3-torch/commit/bd49e41f7a1ac050a070b4ad8fa1babe21a5155d

error:

File "/home/jz/miniconda3/envs/py39/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call
 .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.


<img width="1800" alt="image" src="https://github.com/NM512/dreamerv3-torch/assets/382863/f0b063d3-1cbf-4e6c-b189-938e901bdaba">

**Comment by zdx3578** [comment]
where config  eval_length   train_length  ? default. 500.0 how  change? @NM512

**Comment by NM512** [comment]
You mean this one?
https://github.com/NM512/dreamerv3-torch/blob/f3fe3a872e1fa8da8e804675c38e1bc1439311fd/configs.yaml#L26

**Comment by zdx3578** [comment]
> You mean this one?
> 
> https://github.com/NM512/dreamerv3-torch/blob/f3fe3a872e1fa8da8e804675c38e1bc1439311fd/configs.yaml#L26

this is 1000,not 500, let me test.

**Comment by zdx3578** [comment]
every experience in log dir will save config para in file ?

**Comment by zdx3578** [comment]
https://github.com/zdx3578/dreamerv3-torch/commit/bd49e41f7a1ac050a070b4ad8fa1babe21a5155d  this code eval some score,bug train always retrun just  0 or 1 , some wrong ?

![image](https://github.com/NM512/dreamerv3-torch/assets/382863/da5d752a-adb8-4d8e-bedf-35cc09b3367f)

![image](https://github.com/NM512/dreamerv3-torch/assets/382863/6df48d73-f1eb-4893-849a-5b9465eadd48)

**Comment by zdx3578** [comment]
test a atari game

![image](https://github.com/NM512/dreamerv3-torch/assets/382863/7014144f-65b8-48ab-a854-b6047c9075ee)

**Comment by zdx3578** [comment]
stpn include long and short  memory；dreamer have deter and stoch ； use stpn only replace deter，no imporve；
