### ISSUE TITLE
Errors in exploration.py

### ISSUE THREAD

**Issue by si0wang** [NM512/dreamerv3-torch#3]
Thanks very much for this implementation! I found that there is still "tf" functions in exploration.py.

**Comment by NM512** [comment]
Thanks for letting me know that.
All tf functions have been replaced to corresponding functions in pytorch in [this commit](https://github.com/NM512/dreamerv3-torch/commit/57ac1c11d394c7922aab579d437436bd55347c3f).
But note that the performance of plan2explore has not been checked.
