### ISSUE TITLE
networks.py line 808 variable "mean" not defined

### ISSUE THREAD

**Issue by lgh0504** [NM512/dreamerv3-torch#31]
elif self._dist == "normal_1":
            x = self._dist_layer(x)
            dist = torchd.normal.Normal(mean, 1)
            dist = tools.ContDist(torchd.independent.Independent(dist, 1))

         the variable "mean" is not defined

**Comment by NM512** [comment]
Thank you for bringing that to my attention.
I have fixed the bug.
