### ISSUE TITLE
Set agent to eval mode in simulate function

### ISSUE THREAD

**Issue by zoharri** [NM512/dreamerv3-torch#33]
Hi! thank you for the great work!
In line 165 in tools.py (the simulate function), you call the agent as follows:
` action, agent_state = agent(obs, done, agent_state)`

I think this should be:
 ` action, agent_state = agent(obs, done, agent_state, not is_eval)`
 right?
  
 Thanks!

**Comment by NM512** [comment]
Hi,

Thank you for your comment.
I believe the policy is set to evaluation mode by the following line of code before calling the simulate function.https://github.com/NM512/dreamerv3-torch/blob/d94a719421401baab3a38696ab23f15b9c98b4ae/dreamer.py#L330
