### ISSUE TITLE
[Feature Request] Add “set seed everywhere” feature to ensure reproducibility of experiments

### ISSUE THREAD

**Issue by ygjldd** [NM512/dreamerv3-torch#34]
Hi,
Thanks very much for this implementation!
Currently, the project does not have a consistent way of setting the random seed for torch and other random number generators. This can lead to different results for the same experiment. To address this issue, I propose to add a feature that allows the user to set the seed for all relevant modules and libraries at the beginning of the experiment. Like this : https://github.com/thuml/Flowformer/blob/bc8c4d22b48dde62519f086ba6a9f22463277741/Flowformer_RL/utils.py#L16
This way, we can ensure that the results are reproducible and reliable.
I hope this suggestion will be helpful for the project.

**Comment by NM512** [comment]
Hi,
Thank you for your suggestion!
I've added the option for a deterministic run at [this commit](https://github.com/NM512/dreamerv3-torch/commit/606ec8af8c096cb49658df70a85a0ca66ea6c3c8).

You can use it like this:
```
python dreamer.py --config dmc_vision --logdir ./logdir/test --deterministic_run True
```

I was able to verify deterministic results among the DMC proprio, DMC vision, Atari100k, and MemoryMaze environments. However, it seems that the deterministic run is not supported for the Minecraft and Crafter environments. Please check [this issue](https://github.com/minerllabs/minerl/issues/303) if you want to know the status of support for full-deterministic runs in MineRL.
