### ISSUE TITLE
multiple environments

### ISSUE THREAD

**Issue by neale** [NM512/dreamerv3-torch#4]
Hi there, I'm still in the process of digging at this issue, but maybe you know a quick fix
I got an error when I set `--envs` to be greater than 1 in both atari and dmc environments

Here's the error + results of running with more than 1 env: `python3 dreamer.py --configs defaults --task dmc_walker_walk --logdir results/walker --envs 2`

```
Logdir results/walker
Create envs.
Prefill dataset (2500 steps).
Traceback (most recent call last):
  File "dreamer.py", line 375, in <module>
    main(parser.parse_args(remaining))
  File "dreamer.py", line 330, in main
    tools.simulate(random_agent, train_envs, prefill)
  File "/<path>/dreamerv3-torch/tools.py", line 146, in simulate
    action = [
  File "/<path>/dreamerv3-torch/tools.py", line 147, in <listcomp>
    {k: np.array(action[k][i].detach().cpu()) for k in action}
  File "/<path>/dreamerv3-torch/tools.py", line 147, in <dictcomp>
    {k: np.array(action[k][i].detach().cpu()) for k in action}
IndexError: index 1 is out of bounds for dimension 0 with size 1
```

EDIT: I got through that specific error, but there are shape errors all over the place when `--envs > 1`

**Comment by NM512** [comment]
Thanks for letting me know the bug.
That bug has been fixed in [this commit](https://github.com/NM512/dreamerv3-torch/commit/8bd69bfcd4f0e37dbe73844447c58d288035079b).

**Comment by neale** [comment]
thanks!

**Comment by neale** [comment]
Hi again, 

I'm hitting another error in the multi env setup, in a fresh copy of the repo, inside sample_episodes:
![image](https://user-images.githubusercontent.com/2781245/230693786-21a43ee9-3217-4725-aa7f-5dfe02ed780d.png)

run command is : `python3 dreamer.py --configs defaults --task dmc_walker_walk --logdir logdir/dmc_walker_walk`

For now I just break out of the while loop if all the episodes are empty.
This error does not occur if we just use one env.

**Comment by NM512** [comment]
Thanks for letting me know the bug again.
That bug has been fixed in [this commit](https://github.com/NM512/dreamerv3-torch/commit/55ed69bdf71d09eefe4b7701d4656f3c7631531c).

**Comment by neale** [comment]
Just ran 200k steps with 8 envs, looks good!
