### ISSUE TITLE
Question of env

### ISSUE THREAD

**Issue by Caixy1113** [NM512/dreamerv3-torch#41]
Hi,NM512,im trying to run the training experiments but face some question below, it seems caused by torch2.0,how could I fix it?Hope to your reply.

> (dreamerv3) cxy@amin001-SYS-7049GP-TRT:~/dreamerv3-torch-main$ python3 dreamer.py --configs dmc_vision --task dmc_walker_walk --logdir ./logdir/dmc_walker_walk
> Logdir logdir/dmc_walker_walk
> Create envs.
> /home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/gym/spaces/box.py:127: UserWarning: WARN: Box bound precision lowered by casting to float32
>   logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
> Prefill dataset (500 steps).
> Logger: (5000 steps).
> Simulate agent.
> Encoder CNN shapes: {'image': (64, 64, 3)}
> Encoder MLP shapes: {}
> Decoder CNN shapes: {'image': (64, 64, 3)}
> Decoder MLP shapes: {}
> [5000] 
> Start evaluation.
> Traceback (most recent call last):
>   File "/home/cxy/dreamerv3-torch-main/dreamer.py", line 392, in <module>
>     main(parser.parse_args(remaining))
>   File "/home/cxy/dreamerv3-torch-main/dreamer.py", line 334, in main
>     tools.simulate(
>   File "/home/cxy/dreamerv3-torch-main/tools.py", line 168, in simulate
>     action, agent_state = agent(obs, done, agent_state)
>   File "/home/cxy/dreamerv3-torch-main/dreamer.py", line 90, in __call__
>     policy_output, state = self._policy(obs, state, training)
>   File "/home/cxy/dreamerv3-torch-main/dreamer.py", line 107, in _policy
>     embed = self._wm.encoder(obs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/cxy/dreamerv3-torch-main/networks.py", line 391, in forward
>     outputs.append(self._cnn(inputs))
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/cxy/dreamerv3-torch-main/networks.py", line 526, in forward
>     x = self.layers(x)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
>     input = module(input)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/cxy/dreamerv3-torch-main/networks.py", line 876, in forward
>     ret = F.conv2d(
> RuntimeError: GET was unable to find an engine to execute this computation
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function MjrContext.__del__ at 0x7f94a72fe790>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 633, in __del__
>     self.free()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 625, in free
>     ctx.call(ptr.free)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
>     return self._call_locked(func, *args, **kwargs)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown
> Exception ignored in: <function ContextBase.__del__ at 0x7f94ad232550>
> Traceback (most recent call last):
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 118, in __del__
>     self._free_unconditionally()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/base.py", line 115, in _free_unconditionally
>     self._render_executor.terminate(self._free_on_executor_thread)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 214, in terminate
>     self._call_locked(cleanup_callable)
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
>     return self._executor.submit(func, *args, **kwargs).result()
>   File "/home/cxy/miniconda3/envs/dreamerv3/lib/python3.9/concurrent/futures/thread.py", line 167, in submit
>     raise RuntimeError('cannot schedule new futures after shutdown')
> RuntimeError: cannot schedule new futures after shutdown

**Comment by NM512** [comment]
Hi,

It seems that the error you encountered may be related to the dependencies of DMC (Deep Mind Control). 
Please take a closer look at the dependencies and ensure they are properly configured.
Alternatively, you can consider using Docker as an alternative approach.

Best regards,
NM512

**Comment by sofan110** [comment]
I meet the same problem and I solve it by upgrading my CUDA version to 11.8.
see also  https://github.com/ultralytics/ultralytics/issues/4060#issuecomment-1721726903
