### ISSUE TITLE
Multigpus

### ISSUE THREAD

**Issue by realjoenguyen** [NM512/dreamerv3-torch#51]
Hi, 
How to extend the codebase to multi-gpus ? Seems like non-trivial to do that? 
Thank you,

**Comment by NM512** [comment]
Hello,

One option worth exploring is leveraging the implementation of RLlib, as it inherently supports multi-GPU training. RLlib provides a robust framework for reinforcement learning, and its multi-GPU capabilities can serve as a valuable reference point for your codebase extension.

Moreover, if you can accept TF implementation, you might find [DreamerV3](https://github.com/ray-project/ray/tree/master/rllib/algorithms/dreamerv3) within the RLlib library.
