### ISSUE TITLE
Default hyper Parameters

### ISSUE THREAD

**Issue by JonasGrutter** [NM512/dreamerv3-torch#52]
Hey, I found out that the default shape of the latent space shape for DMC Proprio is 1024 which is  way bigger the the shape of the observations. Can you explain me why ?

**Comment by NM512** [comment]
Thank you for bringing this up. The network size for each task is detailed in [the paper](https://arxiv.org/pdf/2301.04104v1.pdf), particularly in Appendices A and B.

Originally, I intended for the hidden unit size for the size S, including the encoder and decoder, to be 512. However, upon reviewing the original implementation, it appears that a configuration of 1024 x 5 layers was used for the encoder and decoder(not latent space), which I followed from [this specific commit](https://github.com/NM512/dreamerv3-torch/commit/2c7a81a0e2f5f0c7659ba73b0ddbedf2a7e2ecf4).
