### ISSUE TITLE
I ran DreamerV3 with bigger input resolution, but it will be "Killed" after around 325k steps

### ISSUE THREAD

**Issue by Taskii-Lei** [NM512/dreamerv3-torch#59]
I want to run dreamer-v3 on task "hammer" in  meta-world. I editted the config.yaml to :
```
task: 'metaworld_hammer'
size: [256, 256]
batch_size: 28
batch_length: 32
```
Other parameters remain the same as before. 
But I found when it trains around 325k steps, it gonna stop with error "Killed", and no other words.
```
Stderr 2024-06-21, 18:57:00
Logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Stderr 2024-06-21, 19:02:09
Killed
```
I tried several times but all reduced to the same results. I'm really confused.

**Comment by dirkmcpherson** [comment]
Have you checked your memory usage?
