### ISSUE TITLE
ConvDecoder without SymlogDist?

### ISSUE THREAD

**Issue by truncs** [NM512/dreamerv3-torch#8]
It seems like that in the official jax repo the loss function for image is 'mse' and for other vector it is a symlog. Does it make sense to have the dist function default to MSE? Here is the config from the original jax implementation -

```
  decoder: {mlp_keys: '.*', cnn_keys: '.*', act: silu, norm: layer, mlp_layers: 5, mlp_units: 1024, cnn: resnet, cnn_depth: 96, cnn_blocks: 0, image_dist: mse, vector_dist: symlog_mse, inputs: [deter, stoch], resize: stride, winit: normal, fan: avg, outscale: 1.0, minres: 4, cnn_sigmoid: False}
```

**Comment by NM512** [comment]
Thanks for your comment.
That's exactly what I am thinking to modify when I tackle the item of " Add state input capability" in ToDo list. As you might know current code is only capable of image input since state encoder doesn't exist.

By the way, any contributions are welcome! :D
