### ISSUE TITLE
Questions :)

### ISSUE THREAD

**Issue by till2** [NM512/dreamerv3-torch#9]
Hi,

I am currently trying to implement DreamerV2/V3 in PyTorch as well and have encountered some challenges/ am stuck a little bit at various points. I was wondering if you would be open to help me with a few questions. If you can, I would really appreciate it. If you're available, you can reach me on Discord at Till#1064 (preferred) or via email at zemanntill@gmail.com.

Best,
Till

**Comment by NM512** [comment]
Hi,
Sure, I'll do my best to help. 
Since I don't have a Discord account, I'll reach out to you via email instead.
